import NavbarCMS from "../components/Fragements/Navbar/NavbarCMS";
import Provide from "../utils/Provider";
import "./globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Provide>
          <NavbarCMS />
          {children}
        </Provide>
      </body>
    </html>
  );
}
